Total Vehicles =
SUM ( FleetPulseOverview[total_vehicles] )

Active Vehicles =
SUM ( FleetPulseOverview[active] )

Idle Vehicles =
SUM ( FleetPulseOverview[idle] )

Parked Vehicles =
SUM ( FleetPulseOverview[parked] )

Offline Vehicles =
SUM ( FleetPulseOverview[offline] )

Active Vehicle % =
DIVIDE ( [Active Vehicles], [Total Vehicles], 0 )

Trips Today =
SUM ( FleetPulseOverview[total_trips_today] )

Stops Today =
SUM ( FleetPulseOverview[total_stops_today] )

Miles Today =
SUM ( FleetPulseOverview[total_distance_miles] )

Average Trip Duration Hours =
AVERAGE ( FleetPulseOverview[avg_trip_duration_hours] )

Target Trip Duration Hours =
AVERAGE ( FleetPulseOverview[target_trip_duration_hours] )

Trips Meeting Target =
SUM ( FleetPulseOverview[trips_meeting_target] )

Trips Under Target =
SUM ( FleetPulseOverview[trips_under_target] )

Trip Target Attainment % =
DIVIDE ( [Trips Meeting Target], [Trips Today], 0 )

Average Safety Score =
AVERAGE ( FleetPulseSafetyScores[score] )

High Risk Vehicles =
CALCULATE (
    DISTINCTCOUNT ( FleetPulseSafetyScores[vehicle_id] ),
    FleetPulseSafetyScores[score] < 70
)

Total Safety Events =
SUM ( FleetPulseSafetyScores[event_count] )

Speeding Events =
SUM ( FleetPulseSafetyScores[speeding_events] )

Harsh Braking Events =
SUM ( FleetPulseSafetyScores[harsh_braking_events] )

Harsh Acceleration Events =
SUM ( FleetPulseSafetyScores[harsh_acceleration_events] )

Harsh Cornering Events =
SUM ( FleetPulseSafetyScores[harsh_cornering_events] )

Vehicles With Coordinates =
CALCULATE (
    DISTINCTCOUNT ( FleetPulseVehicles[id] ),
    NOT ISBLANK ( FleetPulseVehicles[latitude] ),
    NOT ISBLANK ( FleetPulseVehicles[longitude] )
)

Location Count =
DISTINCTCOUNT ( FleetPulseLocations[name] )

Empty Terminals =
CALCULATE (
    DISTINCTCOUNT ( FleetPulseLocations[name] ),
    FleetPulseLocations[vehicle_count] = 0
)

Last FleetPulse Export =
MAX ( FleetPulseOverview[exported_at] )

Lane Stability Revenue =
SUM ( LaneStabilityCompany[total_revenue] )

Lane Stability Team Revenue =
SUM ( LaneStabilityCompany[team_subset_revenue] )

Weighted Stable Coverage % =
AVERAGE ( LaneStabilityCompany[weighted_stable_cov_pct] )

Baseline Stable Coverage % =
AVERAGE ( LaneStabilityCompany[baseline_weighted_stable_cov_pct] )

Stable Coverage Delta =
AVERAGE ( LaneStabilityCompany[delta_vs_baseline_pct] )

Critical Lanes =
SUM ( LaneStabilityCompany[critical] )

At Risk Lanes =
SUM ( LaneStabilityCompany[at_risk] )

Cross Route Lanes =
SUM ( LaneStabilityCompany[cross_route_lanes] )

Problem Lane Count =
CALCULATE (
    COUNTROWS ( LaneStabilityLanes ),
    LaneStabilityLanes[status] IN { "Critical", "At Risk" }
)

Improving Lane Count =
CALCULATE (
    COUNTROWS ( LaneStabilityTrend ),
    LaneStabilityTrend[trend_type] = "improving"
)

Degrading Lane Count =
CALCULATE (
    COUNTROWS ( LaneStabilityTrend ),
    LaneStabilityTrend[trend_type] = "degrading"
)

Last Lane Stability Export =
MAX ( LaneStabilityCompany[exported_at] )

Known Operating Cost =
SUM ( OperatingCostWeekly[known_operating_cost] )

True Operating Cost =
SUM ( OperatingCostWeekly[true_operating_cost] )

Operating Miles =
SUM ( OperatingCostWeekly[miles] )

Operating Drive Hours =
SUM ( OperatingCostWeekly[drive_hours] )

Known Cost Per Mile =
DIVIDE ( [Known Operating Cost], [Operating Miles] )

True Cost Per Mile =
DIVIDE ( [True Operating Cost], [Operating Miles] )

Known Cost Per Drive Hour =
DIVIDE ( [Known Operating Cost], [Operating Drive Hours] )

True Cost Per Drive Hour =
DIVIDE ( [True Operating Cost], [Operating Drive Hours] )

Operating Cost Complete =
IF ( SELECTEDVALUE ( OperatingCostSummary[complete_cost_available], FALSE () ), 1, 0 )
